# Using this chart assumes that the following services are deployed:
# - user api
# - identity api
# - redis
#
# It also assumes the dictybase-configuration chart has been deployed
# with auth secrets (JWT private key, JWT public key, oauth config).

replicaCount: 1

image:
  repository: dictybase/modware-auth
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: auth-api
  type: NodePort
  port: 9549

# Level of log
logLevel: debug
resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
