# Default values for golang.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: dictybase/modware-auth
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: auth-api
  type: NodePort
  port: 9549

## File name with public key(required)
# publicKey:
#
## File name with private key(required)
# privateKey:
#
## Name of configuration file(https://github.com/dictyBase/authserver#create-configuration-file) holding
## client secrets for various provider(required)
# configFile:

# Level of log
logLevel: debug
resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
